// Nama : Rifki Luthfiandi
// NIM : H1051201060

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojecttokohewanlauthiasonline;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Unknown
 */
public class Shop extends javax.swing.JFrame {

    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
        jLabel4.setText(RegisterAccount.namapengguna + "!");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Shop().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TabelKeranjang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_NamaHewan = new javax.swing.JComboBox<>();
        jTextField_JumlahHewan = new javax.swing.JTextField();
        jTextField_HargaHewan = new javax.swing.JTextField();
        jTextField_SubTotalHargaHewan = new javax.swing.JTextField();
        jButton_TambahKeKeranjangHewan = new javax.swing.JButton();
        jComboBox_Perlengkapan = new javax.swing.JComboBox<>();
        jTextField_JumlahPerlengkapan = new javax.swing.JTextField();
        jTextField_HargaPerlengkapan = new javax.swing.JTextField();
        jTextField_SubTotalHargaPerlengkapan = new javax.swing.JTextField();
        jButton_TambahKeKeranjangPerlengkapan = new javax.swing.JButton();
        jButton_Bersihkan = new javax.swing.JButton();
        jTextField_HargaTotalBarang = new javax.swing.JTextField();
        jTextField_OngkosKirim = new javax.swing.JTextField();
        jTextField_TotalPembayaran = new javax.swing.JTextField();
        jButton_Bayar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(707, 776));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOKO HEWAN LAUT HIAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Silakan pilih item yang akan dipesan :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selamat Datang,");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("namapengguna");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nama Hewan :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jumlah :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Harga :");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sub Total Harga :");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Perlengkapan Lainnya :");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jumlah :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Harga :");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sub Total Harga :");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable_TabelKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Unit", "Jumlah", "Harga", "Sub Total Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable_TabelKeranjang);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Harga Total Barang :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Biaya Ongkos Kirim :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Total Pembayaran :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Keranjang :");

        jComboBox_NamaHewan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Silakan dipilih -", "Ikan Nemo", "Kepiting", "Kuda Laut", "Kura-kura", "Lobster" }));
        jComboBox_NamaHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NamaHewanActionPerformed(evt);
            }
        });

        jTextField_JumlahHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_JumlahHewanActionPerformed(evt);
            }
        });
        jTextField_JumlahHewan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_JumlahHewanKeyTyped(evt);
            }
        });

        jTextField_HargaHewan.setEditable(false);
        jTextField_HargaHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HargaHewanActionPerformed(evt);
            }
        });

        jTextField_SubTotalHargaHewan.setEditable(false);
        jTextField_SubTotalHargaHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SubTotalHargaHewanActionPerformed(evt);
            }
        });

        jButton_TambahKeKeranjangHewan.setText("Tambah ke keranjang");
        jButton_TambahKeKeranjangHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TambahKeKeranjangHewanActionPerformed(evt);
            }
        });

        jComboBox_Perlengkapan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Silakan dipilih -", "Akuarium", "Alat Oksigen Akuarium", "Batu Karang Hias", "Pasir Hias", "Rumput Laut Hias" }));
        jComboBox_Perlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PerlengkapanActionPerformed(evt);
            }
        });

        jTextField_JumlahPerlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_JumlahPerlengkapanActionPerformed(evt);
            }
        });
        jTextField_JumlahPerlengkapan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_JumlahPerlengkapanKeyTyped(evt);
            }
        });

        jTextField_HargaPerlengkapan.setEditable(false);
        jTextField_HargaPerlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HargaPerlengkapanActionPerformed(evt);
            }
        });

        jTextField_SubTotalHargaPerlengkapan.setEditable(false);
        jTextField_SubTotalHargaPerlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SubTotalHargaPerlengkapanActionPerformed(evt);
            }
        });

        jButton_TambahKeKeranjangPerlengkapan.setText("Tambah ke keranjang");
        jButton_TambahKeKeranjangPerlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TambahKeKeranjangPerlengkapanActionPerformed(evt);
            }
        });

        jButton_Bersihkan.setText("Bersihkan");
        jButton_Bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BersihkanActionPerformed(evt);
            }
        });

        jTextField_HargaTotalBarang.setEditable(false);
        jTextField_HargaTotalBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HargaTotalBarangActionPerformed(evt);
            }
        });

        jTextField_OngkosKirim.setEditable(false);
        jTextField_OngkosKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_OngkosKirimActionPerformed(evt);
            }
        });

        jTextField_TotalPembayaran.setEditable(false);
        jTextField_TotalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TotalPembayaranActionPerformed(evt);
            }
        });

        jButton_Bayar.setText("Bayar");
        jButton_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox_NamaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_JumlahHewan)
                                    .addComponent(jTextField_HargaHewan, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jTextField_SubTotalHargaHewan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox_Perlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField_JumlahPerlengkapan)
                            .addComponent(jTextField_HargaPerlengkapan)
                            .addComponent(jTextField_SubTotalHargaPerlengkapan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216)))
                        .addGap(45, 45, 45)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton_TambahKeKeranjangHewan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_TambahKeKeranjangPerlengkapan)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_Bersihkan)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_HargaTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_OngkosKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_TotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jButton_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox_NamaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Perlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_JumlahHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_JumlahPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_HargaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_HargaPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_SubTotalHargaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SubTotalHargaPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_TambahKeKeranjangHewan)
                            .addComponent(jButton_TambahKeKeranjangPerlengkapan))
                        .addGap(177, 177, 177)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_HargaTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_OngkosKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_TotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Bayar)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 690, 680);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Close.setText("   X");
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        jLabel_Minimize.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jLabel_Minimize.setText("  _");
        jLabel_Minimize.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 624, Short.MAX_VALUE)
                .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Close)
                .addComponent(jLabel_Minimize))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 690, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        // TODO add your handling code here:

        this.setState(1);
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked
    private void setHargaHewan() {
        int harga = 0;
        int pil = jComboBox_NamaHewan.getSelectedIndex();
        switch (pil) {
            case 1:
                harga = 100000;
                break;
            case 2:
                harga = 80000;
                break;
            case 3:
                harga = 150000;
                break;
            case 4:
                harga = 200000;
                break;
            case 5:
                harga = 300000;
                break;
        }
        jTextField_HargaHewan.setText("" + harga);

        // menentukan Sub Total Harga Hewan        
        try {
            int jumlah = Integer.parseInt(jTextField_JumlahHewan.getText());
            jTextField_SubTotalHargaHewan.setText("" + (harga * jumlah));
        } catch (NumberFormatException e) {
            jTextField_SubTotalHargaHewan.setText("0");
        }

    }
    private void jComboBox_NamaHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NamaHewanActionPerformed
        // TODO add your handling code here:

        setHargaHewan();
    }//GEN-LAST:event_jComboBox_NamaHewanActionPerformed

    private void jTextField_JumlahHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_JumlahHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JumlahHewanActionPerformed

    private void jTextField_JumlahHewanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_JumlahHewanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JumlahHewanKeyTyped

    private void jTextField_HargaHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HargaHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HargaHewanActionPerformed

    private void jTextField_SubTotalHargaHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SubTotalHargaHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SubTotalHargaHewanActionPerformed
    private boolean cekJikaKosong(boolean hewan) {
        boolean hasil = false;

        if (hewan == true) {
            if (jTextField_JumlahHewan.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Silakan isi jumlah item 'Hewan' yang akan dipesan.");
                hasil = true;
            }
        } else {
            if (jTextField_JumlahPerlengkapan.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Silakan isi jumlah item 'Perlengkapan Lainnya' yang akan dipesan.");
                hasil = true;
            }
        }
        return hasil;
    }

    public ArrayList namaunit = new ArrayList();
    public ArrayList jumlah = new ArrayList();
    public ArrayList harga = new ArrayList();
    public ArrayList subtotalharga = new ArrayList();

    private void jButton_TambahKeKeranjangHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TambahKeKeranjangHewanActionPerformed
        // TODO add your handling code here:

        if (cekJikaKosong(true) == false) {

            String namaunitItem = jComboBox_NamaHewan.getSelectedItem().toString();

            int hrga = Integer.parseInt(jTextField_HargaHewan.getText());
            int jmlh = Integer.parseInt(jTextField_JumlahHewan.getText());
            jTextField_SubTotalHargaHewan.setText("" + (hrga * jmlh));

            namaunit.add(namaunitItem);
            jumlah.add(jTextField_JumlahHewan.getText());
            harga.add(jTextField_HargaHewan.getText());
            subtotalharga.add(jTextField_SubTotalHargaHewan.getText());

            setTabelKeranjang();

        }
    }//GEN-LAST:event_jButton_TambahKeKeranjangHewanActionPerformed
    private void setHargaPerlengkapanLainnya() {
        int harga = 0;
        int pil = jComboBox_Perlengkapan.getSelectedIndex();
        switch (pil) {
            case 1:
                harga = 120000;
                break;
            case 2:
                harga = 70000;
                break;
            case 3:
                harga = 50000;
                break;
            case 4:
                harga = 10000;
                break;
            case 5:
                harga = 20000;
                break;
        }
        jTextField_HargaPerlengkapan.setText("" + harga);

// menentukan Sub Total Harga Perlengkapan Lainnya        
        try {
            int jumlah = Integer.parseInt(jTextField_JumlahPerlengkapan.getText());
            jTextField_SubTotalHargaPerlengkapan.setText("" + (harga * jumlah));
        } catch (NumberFormatException e) {
            jTextField_SubTotalHargaPerlengkapan.setText("0");
        }
    }
    private void jComboBox_PerlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PerlengkapanActionPerformed
        // TODO add your handling code here:

        setHargaPerlengkapanLainnya();
    }//GEN-LAST:event_jComboBox_PerlengkapanActionPerformed

    private void jTextField_JumlahPerlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_JumlahPerlengkapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JumlahPerlengkapanActionPerformed

    private void jTextField_JumlahPerlengkapanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_JumlahPerlengkapanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JumlahPerlengkapanKeyTyped

    private void jTextField_HargaPerlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HargaPerlengkapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HargaPerlengkapanActionPerformed

    private void jTextField_SubTotalHargaPerlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SubTotalHargaPerlengkapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SubTotalHargaPerlengkapanActionPerformed

    private void jButton_TambahKeKeranjangPerlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TambahKeKeranjangPerlengkapanActionPerformed
        // TODO add your handling code here:

        if (cekJikaKosong(false) == false) {

            String namaunitItem = jComboBox_Perlengkapan.getSelectedItem().toString();

            int hrga = Integer.parseInt(jTextField_HargaPerlengkapan.getText());
            int jmlh = Integer.parseInt(jTextField_JumlahPerlengkapan.getText());
            jTextField_SubTotalHargaPerlengkapan.setText("" + (hrga * jmlh));

            namaunit.add(namaunitItem);
            jumlah.add(jTextField_JumlahPerlengkapan.getText());
            harga.add(jTextField_HargaPerlengkapan.getText());
            subtotalharga.add(jTextField_SubTotalHargaPerlengkapan.getText());

            setTabelKeranjang();

        }
    }//GEN-LAST:event_jButton_TambahKeKeranjangPerlengkapanActionPerformed
    private void setTabelKeranjang() {

        int hargatotalbarang = 0;
        int ongkoskirim = 0;
        int totalpembayaran = 0;

        DefaultTableModel tab = new DefaultTableModel();
        tab.addColumn("Nama Unit");
        tab.addColumn("Jumlah");
        tab.addColumn("Harga");
        tab.addColumn("Sub Total Harga");

        for (int n = 0; n < namaunit.size(); n++) {
            hargatotalbarang = hargatotalbarang + Integer.parseInt(subtotalharga.get(n).toString());

            tab.addRow(new Object[]{
                namaunit.get(n),
                jumlah.get(n),
                harga.get(n),
                subtotalharga.get(n)
            });
        }

        jTable_TabelKeranjang.setModel(tab);

        ongkoskirim = 30000;
        totalpembayaran = (int) (hargatotalbarang + ongkoskirim);

        jTextField_HargaTotalBarang.setText("Rp " + hargatotalbarang);
        jTextField_OngkosKirim.setText("Rp 30000");
        jTextField_TotalPembayaran.setText("Rp " + totalpembayaran);

    }
    private void jButton_BersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BersihkanActionPerformed
        // TODO add your handling code here:

        namaunit.clear();
        jumlah.clear();
        harga.clear();
        subtotalharga.clear();

        setTabelKeranjang();

        jTextField_HargaTotalBarang.setText("");
        jTextField_OngkosKirim.setText("");
        jTextField_TotalPembayaran.setText("");
    }//GEN-LAST:event_jButton_BersihkanActionPerformed

    private void jTextField_HargaTotalBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HargaTotalBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HargaTotalBarangActionPerformed

    private void jTextField_OngkosKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_OngkosKirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_OngkosKirimActionPerformed

    private void jTextField_TotalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TotalPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TotalPembayaranActionPerformed
    private boolean cekJikaKosong2(boolean harga) {
        boolean hasil = false;

        if (harga == true) {
            if (jTextField_HargaTotalBarang.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Item yang akan dibayar belum dipilih");
                hasil = true;
            }
        }
        return hasil;
    }
    private void jButton_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BayarActionPerformed
        // TODO add your handling code here:

        if (cekJikaKosong2(true) == false) {

            JOptionPane.showMessageDialog(null, "Pembayaran berhasil! Item pesanan Anda sedang diproses untuk pengiriman. Anda akan otomatis keluar dari aplikasi.");

            System.exit(0);
        }
    }//GEN-LAST:event_jButton_BayarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Bayar;
    private javax.swing.JButton jButton_Bersihkan;
    private javax.swing.JButton jButton_TambahKeKeranjangHewan;
    private javax.swing.JButton jButton_TambahKeKeranjangPerlengkapan;
    private javax.swing.JComboBox<String> jComboBox_NamaHewan;
    private javax.swing.JComboBox<String> jComboBox_Perlengkapan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_TabelKeranjang;
    private javax.swing.JTextField jTextField_HargaHewan;
    private javax.swing.JTextField jTextField_HargaPerlengkapan;
    private javax.swing.JTextField jTextField_HargaTotalBarang;
    private javax.swing.JTextField jTextField_JumlahHewan;
    private javax.swing.JTextField jTextField_JumlahPerlengkapan;
    private javax.swing.JTextField jTextField_OngkosKirim;
    private javax.swing.JTextField jTextField_SubTotalHargaHewan;
    private javax.swing.JTextField jTextField_SubTotalHargaPerlengkapan;
    private javax.swing.JTextField jTextField_TotalPembayaran;
    // End of variables declaration//GEN-END:variables
}
